# Generated by Django 3.1.7 on 2021-03-02 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_auto_20210301_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_owner', to=settings.AUTH_USER_MODEL)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_reciever', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'reciever')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='inbox',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to='message.inbox'),
        ),
    ]
