# Generated by Django 3.1.7 on 2021-03-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20210302_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='inbox',
        ),
        migrations.AddField(
            model_name='message',
            name='owner_inbox',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_inbox_messages', to='message.inbox'),
        ),
        migrations.AddField(
            model_name='message',
            name='reciever_inbox',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_inbox_messages', to='message.inbox'),
        ),
    ]
