# Generated by Django 3.1.7 on 2021-03-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20210303_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='owner_inbox',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_messages', to='message.inbox'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever_inbox',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_messages', to='message.inbox'),
        ),
        migrations.AlterUniqueTogether(
            name='inbox',
            unique_together=set(),
        ),
    ]
