# Generated by Django 3.1.7 on 2021-03-03 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0005_auto_20210303_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inbox',
            unique_together={('owner', 'reciever')},
        ),
    ]
