# Generated by Django 3.1.7 on 2021-03-13 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210307_1319'),
        ('message', '0006_auto_20210303_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
