# Generated by Django 3.1.7 on 2021-03-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210307_1319'),
        ('message', '0007_auto_20210313_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
