# Generated by Django 3.1.7 on 2021-03-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20210315_1336'),
        ('post', '0008_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
