# Generated by Django 3.1.7 on 2021-03-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0006_auto_20210301_2310'),
        ('message', '0006_auto_20210303_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.like')),
            ],
        ),
        migrations.CreateModel(
            name='InboxNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='message.inbox')),
            ],
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.comment')),
            ],
        ),
    ]
