# Generated by Django 3.1.7 on 2021-03-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210307_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentnotification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='likenotification',
            name='created_at',
        ),
    ]
