# Generated by Django 3.1.7 on 2021-03-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_follow'),
        ('notification', '0003_auto_20210307_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.follow')),
            ],
        ),
    ]
