# Generated by Django 3.1.7 on 2021-03-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_follow'),
        ('notification', '0004_follownotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follownotification',
            name='follow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.follow'),
        ),
    ]
