# Generated by Django 3.1.7 on 2021-03-08 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20210221_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
