# Generated by Django 3.1.7 on 2021-03-25 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_auto_20210315_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('owner', 'reciever')},
        ),
    ]
